public class Question {
	String question;
	String[] answers;
	String[] crtAnswers;
	float score;

	Question(String question, String[] answers, String[] crtAnswers, float score){
		this.question = question;
		this.answers = answers;
		this.crtAnswers = crtAnswers;
		this.score = score;
	}
	public static Question[] questions = {
			new Question("Who is known as father of Java Programming Language?", new String[]{"James Gosling", "M. P Java", "Charlell Babbage", "Blais Pascal"}, new String[]{"James Gosling"},10f),
			new Question("Which of the following is not a Java features?", new String[]{"Dynamic", "Architecture Neutral", "Use of pointers", "Object-oriented"}, new String[]{"Use of pointers"},10f),
			new Question("What is byte code in Java?", new String[]{"Code generated by a Java compiler", "Code generated by a Java Virtual Machine", "Name of Java source code file", "Block of code written inside a class"}, new String[]{"Code generated by a Java compiler"},10f),
			new Question("Which of the following are not Java keywords ?", new String[]{"double", "then", "in", "instanceof"}, new String[]{"then", "in"},10f ),
			new Question("Java language was initially called as ________?", new String[]{"Sumatra", "J++", "Oak", "Pine"}, new String[]{"Oak"},10f ),
			new Question("Which one is a template for creating different objects ?", new String[]{"Array", "class", "Method", "Interface"}, new String[]{"class"},10f ),
			new Question("Which of these operators is used to allocate memory to array variable in Java?", new String[]{"alloc", "malloc", "new malloc", "new"}, new String[]{"new"},10f ),
			new Question("Which of these are bitwise operator?", new String[]{"&' Operator", "&=' Operator", "|=' Operator", "<=' Operator"}, new String[]{"&' Operator", "&=' Operator", "|=' Operator"},10f ),
			new Question("Modulus operator (%) can be applied to which of these?", new String[]{"Integers", "Floating - point numbers", "String", "Boolean"}, new String[]{"Integers", "Floating - point numbers"},10f ),
			new Question("Which of the following are the methods of the Thread class?", new String[]{"yield()", "sleep(long msec)", "go()", "stop()"}, new String[]{"yield()", "sleep(long msec)", "stop()"},10f ),

	};
}


